package com.pedrodalben.bigbangessentials.pokemarket.transaction;

public enum PokeMarketCheckpoint {
    AFTER_LISTING_PREPARED, AFTER_POKEMON_REMOVED, AFTER_LISTING_ACTIVATED,
    AFTER_LISTING_RESERVED, BEFORE_DEBIT, AFTER_DEBIT, BEFORE_BUYER_CLAIM, AFTER_BUYER_CLAIM,
    BEFORE_SELLER_CLAIM, AFTER_SELLER_CLAIM, BEFORE_LISTING_SOLD, AFTER_LISTING_SOLD,
    BEFORE_TRANSACTION_COMMIT, AFTER_TRANSACTION_COMMIT, BEFORE_MONEY_CLAIM_CREDIT, AFTER_MONEY_CLAIM_CREDIT,
    BEFORE_TRADE_POKEMON_REMOVAL, AFTER_TRADE_POKEMON_REMOVAL, BEFORE_TRADE_CLAIMS,
    AFTER_TRADE_CLAIMS, BEFORE_TRADE_COMPLETION, AFTER_TRADE_COMPLETION
}
