package com.pedrodalben.bigbangessentials.pokemarket.model;

public enum TradeOperationStatus {
    CREATED, LISTING_RESERVED, OFFER_VALIDATED, OFFER_ESCROW_PENDING, OFFER_IN_ESCROW,
    FEE_PENDING, FEE_CONFIRMED, CLAIMS_PENDING, CLAIMS_CREATED, COMPLETED,
    ROLLBACK_PENDING, REFUND_PENDING, RECONCILIATION_REQUIRED, FAILED
}
