package com.pedrodalben.bigbangessentials.api.gems;

public enum GemsFailure {
    DISABLED,
    INVALID_AMOUNT,
    MAX_BALANCE_EXCEEDED,
    INSUFFICIENT_BALANCE,
    RESERVATION_NOT_FOUND,
    RESERVATION_NOT_ACTIVE,
    RESERVATION_EXPIRED,
    ALREADY_CAPTURED,
    ALREADY_RELEASED,
    IDEMPOTENCY_CONFLICT,
    INVALID_LEASE,
    PERSISTENCE_FAILURE,
    DATA_INTEGRITY_FAILURE,
    EXECUTOR_SATURATED,
    SHUTTING_DOWN,
    UNKNOWN
}
