package com.pedrodalben.bigbangessentials.economy.gems.api;

public enum GemOperationFailure {
    DISABLED,
    INVALID_AMOUNT,
    NEGATIVE_AMOUNT,
    FRACTIONAL_AMOUNT,
    OVERFLOW,
    MAX_BALANCE_EXCEEDED,
    INSUFFICIENT_AVAILABLE_BALANCE,
    RESERVATION_NOT_FOUND,
    RESERVATION_NOT_ACTIVE,
    RESERVATION_EXPIRED,
    RESERVATION_ALREADY_CAPTURED,
    RESERVATION_ALREADY_RELEASED,
    IDEMPOTENCY_CONFLICT,
    INVALID_LEASE,
    PERSISTENCE_FAILURE,
    DATA_INTEGRITY_FAILURE,
    SHUTTING_DOWN,
    UNAUTHORIZED_SOURCE,
    UNKNOWN
}
